receivers:
  apachetomcat:
    endpoint: http://localhost:8080
    interval: 5s
    username: test
    password: test

processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:7070
    send_timestamps: true

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [apachetomcat]
      processors: [batch]
      exporters: [debug, prometheus]

  telemetry:
    logs:
      level: debug
